### ISSUE TITLE
Module not found: Can't resolve 'react-dom/client'

### ISSUE THREAD

**Issue by gabrielkuettel** [perawallet/connect#31]
I upgraded from `0.0.12` to `0.2.0` and when building the client, I get this error:

```
error - ./node_modules/@perawallet/connect/dist/index.js:1:68
Module not found: Can't resolve 'react-dom/client'
```

Using `next 12.1.0` and `react-dom 17.0.2`

**Comment by gabrielkuettel** [comment]
Solved this problem by upgrading `react-dom` to version 18. 

Might still be worthwhile to check why this happens in older versions of React?

**Comment by mucahit** [comment]
Hey @gabrielkuettel, unfortunately, this is expected due to the breaking change between `react-dom@17` and `react-dom@18` versions.

We've tried to explain it to the developers in the release notes. If you don't have a chance to upgrade `react-dom@18` we're recommending you to stay `@perawallet/connect@0.1.6` version instead of `0.2.0`

Many thanks for your contributions!
